### list_numpy_tidbits

In [22]:
import numpy as np

In [23]:
x = [4, 3, 5, 7, 10, 11, 24, 67] # say we want to grab the index of 10 from this...

In [24]:
np.where(x == 10) # using np.where(), but it returns nothing?

(array([], dtype=int64),)

In [25]:
x_np = np.array(x) # have to convert to np.array() first!
x_np

array([ 4,  3,  5,  7, 10, 11, 24, 67])

In [26]:
np.where(x_np == 10) # now it works!

(array([4]),)

In [28]:
x * 2 # also a major difference between numpy arrays and lists is that lists replicate itself with multiplication

[4, 3, 5, 7, 10, 11, 24, 67, 4, 3, 5, 7, 10, 11, 24, 67]

In [31]:
x_np * 2 # while numpy arrays actually performs the multiplication on each value

array([  8,   6,  10,  14,  20,  22,  48, 134])